x-common-settings: &common-settings
  restart: unless-stopped

x-common-args: &common-args
  DOMAIN_NAME: ${DOMAIN_NAME}

services:
  nginx:
    container_name: nginx
    <<: *common-settings
    build:
      context: ./requirements/nginx
      args:
        <<: *common-args
        CERT_DIR: /etc/nginx/certs
    ports:
      - "443:443"
    volumes:
      - certs-data:/etc/nginx/certs:ro
    networks:
      - frontend

  wordpress:
    container_name: wordpress
    <<: *common-settings
    build:
      context: ./requirements/wordpress
      args:
        <<: *common-args
        BR_VERSION: 1.23.2 # WP 6.4.3
        INSTALL_DIR: /var/www/wordpress
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
    volumes:
      - wp-data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend

  mariadb:
    container_name: mariadb
    <<: *common-settings
    build:
      context: ./requirements/mariadb
    environment:
      DB_ROOT_PASS: ${DB_ROOT_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  redis:
    <<: *common-settings
    build:
      context: ./requirements/redis
    networks:
      - backend

  ftp:
    <<: *common-settings
    build:
      context: ./requirements/ftp
    volumes:
      - /home/${LOGIN}/data/wordpress:/home/ftpuser/wordpress
    networks:
      - backend

  adminer:
    <<: *common-settings
    build:
      context: ./requirements/adminer
    ports:
      8888
    networks:
      - backend

  varnish:
    <<: *common-settings
    build:
      context: ./requirements/varnish
    depends_on:
      - wordpress
    networks:
      - frontend

networks:
  frontend:
    name: frontend
  backend:
    name: backend

volumes:
  certs-data:
    name: certs-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CERTS_DATA}
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_DATA}
  db-data:
    name: db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_DATA}
