x-common-settings: &common-settings
  restart: unless-stopped

x-common-args: &common-args
  DOMAIN_NAME: ${DOMAIN_NAME}
  EMAIL: ${EMAIL}

services:
  nginx:
    container_name: nginx
    <<: *common-settings
    build:
      context: ./requirements/nginx
      args:
        <<: *common-args
        CERT_DIR: /etc/nginx/certs
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CERT_DIR: /etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs-data:/etc/nginx/certs
      - wp-data:/srv/wordpress
    networks:
      - frontend
    develop:
      watch:
        - path: ./requirements/nginx
          action: rebuild

  wordpress:
    container_name: wordpress
    <<: *common-settings
    build:
      context: ./requirements/wordpress
      args:
        <<: *common-args
        INSTALL_DIR: /srv/wordpress
    environment:
      <<: *common-args
      BR_VERSION: 1.23.2 # WP 6.4.3
      INSTALL_DIR: /srv/wordpress
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      REDIS_HOST: redis
      REDIS_PASS: ${REDIS_PASS}
    volumes:
      - wp-data:/srv/wordpress
    depends_on:
      - mariadb
      - redis
    networks:
      - frontend
      - backend

  mariadb:
    container_name: mariadb
    <<: *common-settings
    build:
      context: ./requirements/mariadb
    environment:
      DB_ROOT_PASS: ${DB_ROOT_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  redis:
    container_name: redis
    <<: *common-settings
    build:
      context: ./requirements/redis
    environment:
      REDIS_PASS: ${REDIS_PASS}
    volumes:
      - redis-data:/data
    networks:
      - backend

  ftp:
    container_name: ftp
    <<: *common-settings
    build:
      context: ./requirements/vsftp
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASS: ${FTP_PASS}
    volumes:
      - wp-data:/srv/wordpress
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - frontend

networks:
  frontend:
    name: frontend
  backend:
    name: backend

volumes:
  certs-data:
    name: certs-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CERTS_DATA}
  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_DATA}
  db-data:
    name: db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_DATA}
  redis-data:
    name: redis-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${REDIS_DATA}
